### ISSUE TITLE
Dataset not found

### ISSUE THREAD

**Issue by AsimFayyazRaja** [susantabiswas/TriggerWordAssistant#1]
Hi, can you kindly tell me where can I find the dataset?

![image](https://user-images.githubusercontent.com/28213136/77815990-0ad67200-70e1-11ea-8be9-796d0a6d6eb1.png)

**Comment by susantabiswas** [comment]
@AsimMessi sorry but I dont have the dataset now, it is available in the coursera specialization course material.
